name: Gerar APK (Estável)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar Código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # AQUI ESTÁ A CORREÇÃO:
    # Forçamos o Gradle 8.2 que é 100% compatível com o Android
    - name: Configurar Gradle 8.2
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Compilar APK
      run: gradle assembleDebug --no-daemon

    - name: Upload do APK Pronto
      uses: actions/upload-artifact@v4
      with:
        name: App-PDF-Converter
        path: app/build/outputs/apk/debug/app-debug.apk
